### ISSUE TITLE
When --singularity option used, to run node.js using singularity

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/cwltool#1188] opened 2019-09-04 15:01 UTC
When --singularity option used,
 node.js do not run with docker.

Such a case,
Docker is not available, Singularity is available.

**Comment by s-hoyt** [comment] 2020-11-02 22:42
Hello,

I am also having an issue running cwl with singularity, because of the javascript requirement. This is my exact error (using --singularity):

ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim

**Comment by mr-c** [comment] 2020-11-03 13:52
Hello @s-hoyt , until this issue is fixed you can work around this problem by locally installing [Node.js](https://nodejs.org/en/download/)

**Comment by mr-c** [comment] 2020-12-06 09:36
Closing this issue as it is a duplicate of https://github.com/common-workflow-language/cwltool/issues/803

**Closed by mr-c** 2020-12-06 09:36 UTC
