### ISSUE TITLE
cwltool failed to check singularity version

### ISSUE THREAD

**Issue by hubentu** [common-workflow-language/cwltool#1332] opened 2020-07-30 16:41 UTC
The `singularity.py` tries to check the version of singularity with function `get_version`, but it didn't work for current singularity 3.6.
I have tried to install singularity from the source and from miniconda. They neither give me a regular version number, but `singularity version 47b018f-dirty`, which can't be handled by `get_version`. Thanks!

```
$cwltool --singularity tool.cwl tool.yml
ERROR Got workflow error
Traceback (most recent call last):
  File "/home/qiang/miniconda3/lib/python3.8/site-packages/cwltool/executors.py", line 257, in run_jobs
    job.run(runtime_context)
  File "/home/qiang/miniconda3/lib/python3.8/site-packages/cwltool/job.py", line 828, in run
    (runtime, cidfile) = self.create_runtime(env, runtimeContext)
  File "/home/qiang/miniconda3/lib/python3.8/site-packages/cwltool/singularity.py", line 394, in create_runtime
    if is_version_3_1_or_newer():
  File "/home/qiang/miniconda3/lib/python3.8/site-packages/cwltool/singularity.py", line 77, in is_version_3_1_or_newer
    return int(version[0]) >= 4 or (int(version[0]) == 3 and int(version[1]) >= 1)
ValueError: invalid literal for int() with base 10: '47b018f-dirty\n'
```

## Your Environment
* cwltool version: 
3.0.20200724003302

* singularity version:
$singularity --version
singularity version 47b018f-dirty

**Comment by mr-c** [comment] 2020-07-31 08:25
Hello @hubentu 

I'm not able to reproduce your issue with Singularity version 3.6.1 when building from their source release:

```
$ singularity --version
singularity version 3.6.1
$ singularity version
3.6.1
```

Nor from building the latest from their development branch
```
$ git checkout master && git pull
$ ./mconfig &&   cd ./builddir &&   make
$ ./singularity --version
singularity version 3.6.1+3-gb94fa3544
$ ./singularity version
3.6.1+3-gb94fa3544
```

However, if I delete all the tags from my local git  repository, then I get a result similar to yours:
```
$ git tag | xargs git tag -d
$ ./mconfig &&   cd ./builddir &&   make
$ ./singularity version
b94fa3544
$ ./singularity --version
singularity version b94fa3544
```

Can you `git pull --tags` in your local Singularity repository, rebuild Singularity, and let us know if that fixes the issue for you?

**Comment by hubentu** [comment] 2020-07-31 14:18
Hi @mr-c , you are right. Thanks! 
Using `export VERSION=3.6.1` before comping from source also solves this problem.
The conda binary version still has this problem.
````
$conda install singularity=3.6.1
$singularity version
47b018f-dirty
```

**Comment by mr-c** [comment] 2020-07-31 14:31
@hubentu Thanks for confirming. I've opened https://github.com/conda-forge/singularity-feedstock/issues/22 wit the conda people and I'll close this issue so we can follow up with them, there.

**Closed by mr-c** 2020-07-31 14:31 UTC
Labels: status/awaiting user response
