### ISSUE TITLE
pkg_resources.DistributionNotFound: cwltool

### ISSUE THREAD

**Issue by fbreitwieser** [common-workflow-language/cwltool#495] opened 2017-07-23 10:19 UTC
I installed cwtool using pip with `sudo pip install cwlref-runner`. When I run `cwltool`, I get the following error:
```
$ cwltool
Traceback (most recent call last):
  File "/usr/bin/cwltool", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/cwltool/main.py", line 762, in main
    _logger.info(versionfunc())
  File "/usr/lib/python2.7/site-packages/cwltool/main.py", line 666, in versionstring
    pkg = pkg_resources.require("cwltool")
  File "/usr/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cwltool
```

## Environment
```
$ pip show cwltool
Version: 1.0.20170721221557
$ uname -a  ## It's CentOS
Linux mydomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.5
```

**Comment by manu-chroma** [comment] 2017-07-23 10:39
@fbreitwieser I would highly suggest installing ``cwltool`` in a new virtual environment and see if you're still getting the same error. 

I tested the version you've specified and it works as intended inside a virtual env.

**Comment by manu-chroma** [comment] 2017-07-25 17:30
@fbreitwieser Can you confirm if your issue is resolved or not? Thanks.

**Comment by mr-c** [comment] 2017-08-04 09:36
I'm closing this issue for now -- @fbreitwieser feel free to re-open this if using a `virtualenv` doesn't solve your problem.

**Closed by mr-c** 2017-08-04 09:36 UTC
Labels: status/awaiting user response
